### ISSUE TITLE
Aboritng connection with RteCtrl server

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [3mdeb/RteCtrl#10]
**RTE OS version**
v0.7.1

**Brief summary**
During performing automated tests with power control I note, that sometimes the connection with the API server is unexpectedly broken.

**How reproducible**
From time to time.

**Additional context**

Log with bug description:

`traceback (most recent call last):
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/RequestsLibrary/RequestsKeywords.py", line 731, in patch_request
    response = self._common_request(
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/RequestsLibrary/RequestsKeywords.py", line 938, in _common_request
    resp = method_function(
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/requests/sessions.py", line 601, in patch
    return self.request('PATCH', url, data=data, **kwargs)
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/psulewski/Desktop/testing-infra/pcengines-apu2/open-firmware-rte/robot-venv/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

**Comment by TomaszAIR** [comment]
@sulewskiprzemyslaw could you please provide commands how to reproduce the error?

**Comment by sulewskiprzemyslaw** [comment]
This is the log from RobotFramework in which we have automated tests. If it suits you, I might try to isolate this command.

Log with this file you could find under this [link](https://cloud.3mdeb.com/index.php/s/nMEG4oyd5aJkcX3). The test case with this bug is SDD1.1 in Sd-detect test suite

**Comment by TomaszAIR** [comment]
@sulewskiprzemyslaw If I understand the log correctly, RteCtrl crashes from time to time when we get pin 0 status and then try to change it using API?

I will run the test by getting status and changing it using the following script
```
#!/bin/bash

echo "RTE api test"
RTE_IP="127.0.0.1"

while [ 1 ]
do
  echo "GET and sleep 1"
  curl "http://$RTE_IP:8000/api/v1/gpio/0"
  sleep 1
  echo "PATCH and sleep 1"
  curl -X PATCH "http://$RTE_IP:8000/api/v1/gpio/0" -d "{\"state\":0}"
  sleep 1
  echo "GET and sleep 2"
  curl "http://$RTE_IP:8000/api/v1/gpio/0"
  sleep 2
  echo "PATCH and sleep 4"
  curl -X PATCH "http://$RTE_IP:8000/api/v1/gpio/0" -d "{\"state\":1}"
  sleep 4
done
```

**Comment by TomaszAIR** [comment]
Test did not return any error so I would say that there may be something wrong with test environment. Will try to reproduce the error using robot - but its getting look like the issue is not on RteCtrl side.

**Comment by TomaszAIR** [comment]
@sulewskiprzemyslaw Unfortunately, also using the robot environment, I was not able to reproduce this problem - I think we can close this issue at the moment, if the problem returns, we will try to find its source.

**Comment by macpijan** [comment]
We need confirmation from @sulewskiprzemyslaw .
He has quite reliable (although not that frequent) reproductions, and it was blocking moving forward with the release.

**Comment by macpijan** [comment]
> RteCtrl crashes from time to time when we get pin 0 status and then try to change it using API?

I do not think so it crashes at all. At least it was not reported here. What was reported that Python client library throws out an exception and it looks like a server fault:
- https://code.djangoproject.com/ticket/29849
https://stackoverflow.com/questions/48105448/python-http-server-client-remote-end-closed-connection-without-response-error

**Comment by macpijan** [comment]
Maybe a simple Python `reuests` scripts could be used for trying to reproduce it. And I feel that the problem may be related to requests incoming too quickly, so maybe the `sleeps` in between prevent it from happening.

**Comment by macpijan** [comment]
This gives reproduction:

```
#!/usr/bin/env python3

import requests
import json


while True:
    r = requests.patch('http://IP_HERE:8000/api/v1/gpio/12', data=json.dumps({'state':0}))
    print(r)
    r = requests.patch('http://IP_HERE:8000/api/v1/gpio/12', data=json.dumps({'state':1}))
    print(r)
```

```
...

<Response [200]>
<Response [200]>
<Response [200]>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/projects/3mdeb/tat/./rte-error.py", line 10, in <module>
    r = requests.patch('http://192.168.4.182:8000/api/v1/gpio/12', data=json.dumps({'state':1}))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 149, in patch
    return request('patch', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by sulewskiprzemyslaw** [comment]
@TomaszAIR @macpijan I have prepared a test that does the only thing - switches relay on the RTE. When I have new logs, I will post them under the issue

**Comment by TomaszAIR** [comment]
I tried to look for equivalents from the posted threads in golang net/http (server in golang), without success. The tests that I conducted show:

* the error occurs at random times, sometimes after ~ 2 minutes, sometimes after ~ 13
* error failed to reproduce by calling GET request, only PATCH
* when an error occurs, the server crashes and restarts (due to unit service)

I wonder if the error is due to Garbage Collector (GC) problems. We see in the log

``
 runtime: nelems = 1024 nalloc = 221 previous allocCount = 220 nfreed = 65535 [46/1965]
 fatal error: sweep increased allocation count
``

Which maybe causes the server crash and then the error `Remote end closed connection without response` on the client side.

I also wonder why we call getGpioState in the setGpioState function https://github.com/3mdeb/RteCtrl/blob/master/pkg/restServer/restServer.go#L211 - although it seems to have nothing to do with the problem.

**Comment by macpijan** [comment]
Not reproducible anymore
